### ISSUE TITLE
Uses old phantomjs version. The latest stable release is version 2.0

### ISSUE THREAD

**Issue by akshaymohite** [maxwell/screencap#19]
Code used old phantomjs version (1.9.8)
This needs to be updated as the phantomjs has latest stable version 2.0 - https://github.com/ariya/phantomjs

**Comment by razvan-sv** [comment]
Hello,

That's not the gem, it's the source code. The gem is this one, https://github.com/colszowka/phantomjs-gem, which uses 1.9.8 atm.
